"use client";

import { useState, useMemo } from "react";
import { useSearchParams } from "next/navigation";
import { TopBar } from "@/components/layout/TopBar";
import { DraftStatusBadge } from "@/components/app/StatusBadge";
import { mockDrafts, mockCampaigns } from "@/lib/mock-data";
import { timeAgo, cn } from "@/lib/utils";
import type { OutreachDraft } from "@/lib/types";
import { CheckCircle, XCircle, RotateCcw, Edit3, Bot, Save, X } from "lucide-react";

function DraftEditor({ draft, onClose }: { draft: OutreachDraft; onClose: () => void }) {
  const [editing, setEditing] = useState(false);
  const [body, setBody] = useState(draft.body);
  const [subject, setSubject] = useState(draft.subject);

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-start justify-between p-5 border-b border-white/[0.05]">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <p className="font-poppins text-sm font-semibold text-[#E5ECF6]">{draft.companyName}</p>
            <DraftStatusBadge status={draft.status} />
          </div>
          <p className="text-xs text-[#64748B]">{draft.leadName} · {draft.campaignName}</p>
        </div>
        <button onClick={onClose} className="w-7 h-7 rounded-lg flex items-center justify-center text-[#64748B] hover:text-[#94A3B8] hover:bg-white/[0.05] transition-all">
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Meta */}
      <div className="flex items-center gap-3 px-5 py-2.5 bg-white/[0.01] border-b border-white/[0.05]">
        <div className="flex items-center gap-1.5">
          <Bot className="w-3 h-3 text-[#8B5CF6]" />
          <span className="text-xs text-[#64748B]">Generated by {draft.generatedBy}</span>
        </div>
        <span className="text-xs text-[#4B5563]">·</span>
        <span className="text-xs text-[#64748B]">{timeAgo(draft.generatedAt)}</span>
        <span className="text-xs text-[#4B5563]">·</span>
        <span className="text-xs px-2 py-0.5 rounded-full bg-white/[0.03] border border-white/[0.06] text-[#64748B] font-manrope">
          {draft.tone}
        </span>
      </div>

      <div className="flex-1 overflow-y-auto p-5 space-y-4">
        {/* Subject */}
        <div>
          <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">Subject Line</p>
          {editing ? (
            <input value={subject} onChange={e => setSubject(e.target.value)} className="sv-input w-full text-sm" />
          ) : (
            <p className="text-sm font-manrope font-medium text-[#E5ECF6] p-3 rounded-lg bg-white/[0.02] border border-white/[0.05]">
              {subject}
            </p>
          )}
        </div>

        {/* Opening */}
        <div>
          <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">Opening Line</p>
          <p className="text-sm text-[#94A3B8] font-manrope p-3 rounded-lg bg-white/[0.02] border border-white/[0.05] leading-relaxed">
            {draft.openingLine}
          </p>
        </div>

        {/* Body */}
        <div>
          <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">Message Body</p>
          {editing ? (
            <textarea
              value={body}
              onChange={e => setBody(e.target.value)}
              rows={8}
              className="sv-input w-full text-sm resize-none leading-relaxed"
            />
          ) : (
            <p className="text-sm text-[#94A3B8] font-manrope p-3 rounded-lg bg-white/[0.02] border border-white/[0.05] leading-relaxed whitespace-pre-line">
              {body}
            </p>
          )}
        </div>

        {/* CTA */}
        <div>
          <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">CTA</p>
          <p className="text-sm text-[#94A3B8] font-manrope p-3 rounded-lg bg-white/[0.02] border border-white/[0.05] leading-relaxed">
            {draft.cta}
          </p>
        </div>

        {/* Follow-up */}
        {draft.followUp && (
          <div>
            <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">Follow-up</p>
            <p className="text-sm text-[#94A3B8] font-manrope p-3 rounded-lg bg-white/[0.02] border border-white/[0.05] leading-relaxed italic">
              {draft.followUp}
            </p>
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="p-4 border-t border-white/[0.05] space-y-2">
        {editing ? (
          <div className="flex gap-2">
            <button onClick={() => setEditing(false)} className="flex-1 sv-btn-primary text-xs flex items-center justify-center gap-1.5">
              <Save className="w-3.5 h-3.5" /> Save Changes
            </button>
            <button onClick={() => setEditing(false)} className="sv-btn-outline text-xs">
              Cancel
            </button>
          </div>
        ) : (
          <>
            <button className="w-full flex items-center justify-center gap-1.5 text-xs font-manrope font-medium bg-[#10B981]/10 border border-[#10B981]/20 text-[#10B981] hover:bg-[#10B981]/15 rounded-lg py-2.5 transition-all">
              <CheckCircle className="w-3.5 h-3.5" /> Approve Draft
            </button>
            <div className="grid grid-cols-3 gap-2">
              <button onClick={() => setEditing(true)} className="sv-btn-outline text-xs flex items-center justify-center gap-1">
                <Edit3 className="w-3 h-3" /> Edit
              </button>
              <button className="sv-btn-outline text-xs flex items-center justify-center gap-1">
                <RotateCcw className="w-3 h-3" /> Regen
              </button>
              <button className="sv-btn-outline text-xs flex items-center justify-center gap-1 border-[#EF4444]/20 text-[#EF4444]/70 hover:text-[#EF4444]">
                <XCircle className="w-3 h-3" /> Reject
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

export default function OutreachPage() {
  const searchParams = useSearchParams();
  const campaignIdParam = searchParams.get("campaign");

  const [selectedDraft, setSelectedDraft] = useState<OutreachDraft | null>(mockDrafts[0]);
  const [filter, setFilter] = useState("all");
  const [campaignFilter, setCampaignFilter] = useState(campaignIdParam || "all");

  const filtered = useMemo(() => {
    return mockDrafts.filter(d => {
      const matchStatus = filter === "all" || d.status === filter;
      const matchCampaign = campaignFilter === "all" || d.campaignId === campaignFilter;
      return matchStatus && matchCampaign;
    });
  }, [filter, campaignFilter]);

  return (
    <div className="flex h-full overflow-hidden">
      {/* List */}
      <div className={cn("flex flex-col overflow-hidden border-r border-white/[0.05]", selectedDraft ? "w-96 shrink-0" : "flex-1")}>
        <TopBar
          title="Outreach Review"
          subtitle="Review and approve AI-generated outreach drafts"
          actions={
            <span className="text-xs text-[#F59E0B] font-manrope font-medium bg-[#F59E0B]/10 border border-[#F59E0B]/20 px-2.5 py-1 rounded-full">
              {mockDrafts.filter(d => d.status === "pending_review").length} pending
            </span>
          }
        />

        <div className="flex flex-col gap-2 px-4 py-3 border-b border-white/[0.05]">
          <div className="flex items-center gap-1.5">
            {["all", "pending_review", "approved", "rejected"].map(f => (
              <button key={f} onClick={() => setFilter(f)}
                className={cn(
                  "px-2.5 py-1.5 rounded-lg text-xs font-manrope font-medium capitalize transition-all",
                  filter === f
                    ? "bg-[#3B82F6]/15 text-[#3B82F6] border border-[#3B82F6]/30"
                    : "text-[#64748B] hover:text-[#94A3B8] hover:bg-white/[0.04]"
                )}>
                {f === "all" ? "All" : f.replace("_", " ")}
              </button>
            ))}
          </div>
          
          <div className="relative mt-1">
            <select 
              value={campaignFilter} 
              onChange={e => setCampaignFilter(e.target.value)}
              className="sv-input w-full py-1.5 pl-3 pr-8 text-[11px] appearance-none bg-white/[0.02] border-white/[0.05] text-[#64748B]"
            >
              <option value="all">All Campaigns</option>
              {mockCampaigns.map(c => (
                <option key={c.id} value={c.id}>{c.campaign_name}</option>
              ))}
            </select>
            <Bot className="absolute right-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#64748B] pointer-events-none" />
          </div>
        </div>

        <div className="flex-1 overflow-y-auto">
          {filtered.map(draft => (
            <button key={draft.id} onClick={() => setSelectedDraft(draft)}
              className={cn(
                "w-full text-left p-4 border-b border-white/[0.04] hover:bg-white/[0.02] transition-all",
                selectedDraft?.id === draft.id && "bg-[#3B82F6]/5 border-l-2 border-l-[#3B82F6]"
              )}>
              <div className="flex items-start justify-between gap-2 mb-1.5">
                <p className="text-sm font-manrope font-medium text-[#E5ECF6] truncate">{draft.companyName}</p>
                <DraftStatusBadge status={draft.status} />
              </div>
              <p className="text-xs text-[#64748B] truncate mb-1">{draft.subject}</p>
              <p className="text-xs text-[#4B5563]">{timeAgo(draft.generatedAt)}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Draft editor */}
      {selectedDraft && (
        <div className="flex-1 bg-[#0D1525] overflow-hidden flex flex-col">
          <DraftEditor draft={selectedDraft} onClose={() => setSelectedDraft(null)} />
        </div>
      )}
    </div>
  );
}
