"use client";

import { useState, useMemo, useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { useWorkspace } from "@/components/providers/workspace-provider";
import { createClient } from "@/lib/supabase/client";
import { TopBar } from "@/components/layout/TopBar";
import { DraftStatusBadge } from "@/components/app/StatusBadge";
import { timeAgo, cn } from "@/lib/utils";
import type { OutreachDraft } from "@/lib/types";
import { CheckCircle, XCircle, RotateCcw, Edit3, Bot, Save, X, Loader2 } from "lucide-react";
import { approveDraft, rejectDraft, batchApproveDrafts, sendApprovedOutreach, updateOutreachDraft, regenerateDraft } from "@/lib/actions/workflow";
import { Rocket } from "lucide-react";
import { toast } from "sonner";
import { ConfirmDialog } from "@/components/app/ConfirmDialog";
import { SkeletonRow } from "@/components/app/Skeletons";

function DraftEditor({ 
  draft, 
  onClose, 
  onUpdate,
  onStatusChange 
}: { 
  draft: OutreachDraft; 
  onClose: () => void; 
  onUpdate: () => void;
  onStatusChange: (id: string, status: any) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [isProcessing, setIsProcessing] = useState(false);
  const [body, setBody] = useState(draft.body);
  const [subject, setSubject] = useState(draft.subject);

  const handleApprove = async () => {
    setIsProcessing(true);
    // Optimistic Update
    onStatusChange(draft.id, 'approved');
    try {
      await approveDraft(draft.id);
      toast.success(`Draft for ${draft.companyName} approved.`);
      // onUpdate() is called to ensure consistency but optimistic UI already handled visual part
    } catch (err) {
      console.error(err);
      toast.error("Failed to approve draft.");
      onUpdate(); // Revert on failure
    } finally {
      setIsProcessing(false);
    }
  };

  const handleReject = async () => {
    setIsProcessing(true);
    // Optimistic Update
    onStatusChange(draft.id, 'rejected');
    try {
      await rejectDraft(draft.id);
      toast.info(`Draft for ${draft.companyName} rejected.`);
    } catch (err) {
      console.error(err);
      toast.error("Failed to reject draft.");
      onUpdate(); // Revert on failure
    } finally {
      setIsProcessing(false);
    }
  };

  const handleRegen = async () => {
    setIsProcessing(true);
    try {
      await regenerateDraft(draft.id);
      toast.success("Draft regenerated successfully.");
      onUpdate();
    } catch (err: any) {
      console.error(err);
      toast.error(err.message || "Failed to regenerate draft.");
    } finally {
      setIsProcessing(false);
    }
  };

  const handleSave = async () => {
    setIsProcessing(true);
    try {
      await updateOutreachDraft(draft.id, {
        subject_line: subject,
        message_body: body
      });
      toast.success("Draft changes saved.");
      setEditing(false);
      onUpdate();
    } catch (err) {
      console.error(err);
      toast.error("Failed to save changes.");
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="flex items-start justify-between p-5 border-b border-white/[0.05]">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <p className="font-poppins text-sm font-semibold text-[#E5ECF6]">{draft.companyName}</p>
            <DraftStatusBadge status={draft.status} />
          </div>
          <p className="text-xs text-[#64748B]">{draft.leadName} · {draft.campaignName}</p>
        </div>
        <button onClick={onClose} className="w-7 h-7 rounded-lg flex items-center justify-center text-[#64748B] hover:text-[#94A3B8] hover:bg-white/[0.05] transition-all">
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Meta */}
      <div className="flex items-center gap-3 px-5 py-2.5 bg-white/[0.01] border-b border-white/[0.05]">
        <div className="flex items-center gap-1.5">
          <Bot className="w-3 h-3 text-[#8B5CF6]" />
          <span className="text-xs text-[#64748B]">Generated by {draft.generatedBy}</span>
        </div>
        <span className="text-xs text-[#4B5563]">·</span>
        <span className="text-xs text-[#64748B]">{timeAgo(draft.generatedAt)}</span>
        <span className="text-xs text-[#4B5563]">·</span>
        <span className="text-xs px-2 py-0.5 rounded-full bg-white/[0.03] border border-white/[0.06] text-[#64748B] font-manrope">
          {draft.tone}
        </span>
      </div>

      <div className="flex-1 overflow-y-auto p-5 space-y-4">
        {/* Subject */}
        <div>
          <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">Subject Line</p>
          {editing ? (
            <input value={subject} onChange={e => setSubject(e.target.value)} className="sv-input w-full text-sm" />
          ) : (
            <p className="text-sm font-manrope font-medium text-[#E5ECF6] p-3 rounded-lg bg-white/[0.02] border border-white/[0.05]">
              {subject}
            </p>
          )}
        </div>

        {/* Opening */}
        <div>
          <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">Opening Line</p>
          <p className="text-sm text-[#94A3B8] font-manrope p-3 rounded-lg bg-white/[0.02] border border-white/[0.05] leading-relaxed">
            {draft.openingLine}
          </p>
        </div>

        {/* Body */}
        <div>
          <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">Message Body</p>
          {editing ? (
            <textarea
              value={body}
              onChange={e => setBody(e.target.value)}
              rows={8}
              className="sv-input w-full text-sm resize-none leading-relaxed"
            />
          ) : (
            <p className="text-sm text-[#94A3B8] font-manrope p-3 rounded-lg bg-white/[0.02] border border-white/[0.05] leading-relaxed whitespace-pre-line">
              {body}
            </p>
          )}
        </div>

        {/* CTA */}
        <div>
          <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">CTA</p>
          <p className="text-sm text-[#94A3B8] font-manrope p-3 rounded-lg bg-white/[0.02] border border-white/[0.05] leading-relaxed">
            {draft.cta}
          </p>
        </div>

        {/* Follow-up */}
        {draft.followUp && (
          <div>
            <p className="text-xs font-manrope font-semibold text-[#64748B] uppercase tracking-wider mb-1.5">Follow-up</p>
            <p className="text-sm text-[#94A3B8] font-manrope p-3 rounded-lg bg-white/[0.02] border border-white/[0.05] leading-relaxed italic">
              {draft.followUp}
            </p>
          </div>
        )}
      </div>

      {/* Actions */}
      <div className="p-4 border-t border-white/[0.05] space-y-2">
        {editing ? (
          <div className="flex gap-2">
            <button 
              onClick={handleSave} 
              disabled={isProcessing}
              className="flex-1 sv-btn-primary text-xs flex items-center justify-center gap-1.5 disabled:opacity-50"
            >
              {isProcessing ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Save className="w-3.5 h-3.5" />} 
              Save Changes
            </button>
            <button onClick={() => setEditing(false)} disabled={isProcessing} className="sv-btn-outline text-xs disabled:opacity-50">
              Cancel
            </button>
          </div>
        ) : (
          <>
            <button 
              onClick={handleApprove}
              disabled={isProcessing || draft.status === 'approved'}
              className="w-full flex items-center justify-center gap-1.5 text-xs font-manrope font-medium bg-[#10B981]/10 border border-[#10B981]/20 text-[#10B981] hover:bg-[#10B981]/15 rounded-lg py-2.5 transition-all disabled:opacity-50"
            >
              {isProcessing ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <CheckCircle className="w-3.5 h-3.5" />} 
              {draft.status === 'approved' ? 'Approved' : 'Approve Draft'}
            </button>
            <div className="grid grid-cols-3 gap-2">
              <button onClick={() => setEditing(true)} className="sv-btn-outline text-xs flex items-center justify-center gap-1">
                <Edit3 className="w-3 h-3" /> Edit
              </button>
              <button 
                onClick={handleRegen}
                disabled={isProcessing}
                className="sv-btn-outline text-xs flex items-center justify-center gap-1 disabled:opacity-50"
              >
                {isProcessing ? <Loader2 className="w-3 h-3 animate-spin" /> : <RotateCcw className="w-3 h-3" />} Regen
              </button>
              <button 
                onClick={handleReject}
                disabled={isProcessing || draft.status === 'rejected'}
                className="sv-btn-outline text-xs flex items-center justify-center gap-1 border-[#EF4444]/20 text-[#EF4444]/70 hover:text-[#EF4444] disabled:opacity-50"
              >
                {isProcessing ? <Loader2 className="w-3 h-3 animate-spin" /> : <XCircle className="w-3 h-3" />} Reject
              </button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}

import { PageErrorBoundary } from "@/components/app/PageErrorBoundary";

export default function OutreachPage() {
  return (
    <PageErrorBoundary>
      <OutreachContent />
    </PageErrorBoundary>
  );
}

function OutreachContent() {
  const searchParams = useSearchParams();
  const campaignIdParam = searchParams.get("campaign");

  const [drafts, setDrafts] = useState<OutreachDraft[]>([]);
  const [campaigns, setCampaigns] = useState<any[]>([]);
  const [selectedDraft, setSelectedDraft] = useState<OutreachDraft | null>(null);
  const [filter, setFilter] = useState("all");
  const [campaignFilter, setCampaignFilter] = useState(campaignIdParam || "all");
  const [isLoading, setIsLoading] = useState(true);
  
  // Confirmation States
  const [confirmBatchApprove, setConfirmBatchApprove] = useState(false);
  const [confirmSendBatch, setConfirmSendBatch] = useState(false);

  const { workspace } = useWorkspace();
  const supabase = createClient();

  useEffect(() => {
    async function fetchCampaigns() {
      if (!workspace) return;
      const { data } = await supabase
        .from('campaigns')
        .select('id, campaign_name')
        .eq('workspace_id', workspace.id);
      if (data) setCampaigns(data);
    }
    fetchCampaigns();
  }, [workspace]);

  useEffect(() => {
    fetchDrafts();
  }, [campaignFilter, filter, workspace]);

  // 🚀 Step 13: Real-time Outreach Updates
  useEffect(() => {
    if (!workspace) return;

    const channel = supabase
      .channel(`outreach-updates-${workspace.id}`)
      .on(
        'postgres_changes',
        { event: '*', schema: 'public', table: 'outreach_drafts', filter: `workspace_id=eq.${workspace.id}` },
        () => {
          console.log('[Realtime] Outreach drafts updated');
          fetchDrafts();
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [workspace]);

  const fetchDrafts = async () => {
    try {
      const res = await fetch(`/api/outreach/drafts?campaign=${campaignFilter}&status=${filter}`);
      const data = await res.json();
      setDrafts(data);
      setIsLoading(false);
    } catch (err) {
      console.error(err);
      toast.error("Failed to load drafts.");
    }
  };

  const handleOptimisticStatus = (id: string, status: any) => {
    setDrafts(prev => prev.map(d => d.id === id ? { ...d, status } : d));
    if (selectedDraft?.id === id) {
      setSelectedDraft(prev => prev ? { ...prev, status } : null);
    }
  };

  const handleBatchApprove = async () => {
    if (campaignFilter === 'all') {
      toast.error("Please select a specific campaign to batch approve.");
      return;
    }
    setConfirmBatchApprove(true);
  };

  const executeBatchApprove = async () => {
    setConfirmBatchApprove(false);
    setIsLoading(true);
    try {
      const result = await batchApproveDrafts(campaignFilter);
      if (result.success) {
        toast.success(`Successfully approved ${result.count} drafts.`);
        fetchDrafts();
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to batch approve drafts.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleSendBatch = async () => {
    if (campaignFilter === 'all') {
      toast.error("Please select a specific campaign to send.");
      return;
    }
    const approvedCount = drafts.filter(d => d.status === 'approved').length;
    if (approvedCount === 0) {
      toast.error("No approved drafts found for this campaign.");
      return;
    }
    setConfirmSendBatch(true);
  };

  const executeSendBatch = async () => {
    setConfirmSendBatch(false);
    setIsLoading(true);
    const approvedCount = drafts.filter(d => d.status === 'approved').length;
    try {
      const result = await sendApprovedOutreach(campaignFilter);
      if (result.success) {
        if (result.failedCount > 0) {
          toast.warning(`Sent ${result.sentCount} messages, but ${result.failedCount} failed.`);
        } else {
          toast.success(`Successfully sent ${result.sentCount} messages.`);
        }
        fetchDrafts();
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to send messages.");
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchDrafts();
  }, [filter, campaignFilter]);

  useEffect(() => {
    // Fetch campaigns for filter
    fetch('/api/campaigns')
      .then(res => res.json())
      .then(data => setCampaigns(data))
      .catch(err => {
        console.error(err);
        toast.error("Failed to load campaigns.");
      });
  }, []);

  const activeCampaignName = useMemo(() => {
    return campaigns.find(c => c.id === campaignFilter)?.campaign_name || "Campaign";
  }, [campaigns, campaignFilter]);

  return (
    <div className="flex h-full overflow-hidden">
      {/* List */}
      <div className={cn("flex flex-col overflow-hidden border-r border-white/[0.05]", selectedDraft ? "w-96 shrink-0" : "flex-1")}>
        <TopBar
          title="Outreach Review"
          subtitle="Review and approve AI-generated outreach drafts"
          actions={
            <div className="flex items-center gap-2">
              {campaignFilter !== 'all' && drafts.some(d => d.status === 'pending_review') && (
                <button 
                  onClick={handleBatchApprove}
                  className="sv-btn-primary bg-[#10B981] border-[#10B981] flex items-center gap-1.5 text-[10px] py-1.5 h-auto"
                >
                  <CheckCircle className="w-3 h-3" /> Batch Approve
                </button>
              )}
              {campaignFilter !== 'all' && drafts.some(d => d.status === 'approved') && (
                <button 
                  onClick={handleSendBatch}
                  className="sv-btn-primary bg-[#3B82F6] border-[#3B82F6] flex items-center gap-1.5 text-[10px] py-1.5 h-auto"
                >
                  <Rocket className="w-3 h-3" /> Send All Approved
                </button>
              )}
              <span className="text-xs text-[#F59E0B] font-manrope font-medium bg-[#F59E0B]/10 border border-[#F59E0B]/20 px-2.5 py-1 rounded-full">
                {drafts.filter(d => d.status === "pending_review").length} pending
              </span>
            </div>
          }
        />

        <div className="flex flex-col gap-2 px-4 py-3 border-b border-white/[0.05]">
          <div className="flex items-center gap-1.5">
            {["all", "pending_review", "approved", "rejected"].map(f => (
              <button key={f} onClick={() => setFilter(f)}
                className={cn(
                  "px-2.5 py-1.5 rounded-lg text-xs font-manrope font-medium capitalize transition-all",
                  filter === f
                    ? "bg-[#3B82F6]/15 text-[#3B82F6] border border-[#3B82F6]/30"
                    : "text-[#64748B] hover:text-[#94A3B8] hover:bg-white/[0.04]"
                )}>
                {f === "all" ? "All" : f.replace("_", " ")}
              </button>
            ))}
          </div>
          
          <div className="relative mt-1">
            <select 
              value={campaignFilter} 
              onChange={e => setCampaignFilter(e.target.value)}
              className="sv-input w-full py-1.5 pl-3 pr-8 text-[11px] appearance-none bg-white/[0.02] border-white/[0.05] text-[#64748B]"
            >
              <option value="all">All Campaigns</option>
              {campaigns.map(c => (
                <option key={c.id} value={c.id}>{c.campaign_name}</option>
              ))}
            </select>
            <Bot className="absolute right-2.5 top-1/2 -translate-y-1/2 w-3 h-3 text-[#64748B] pointer-events-none" />
          </div>
        </div>

        <div className="flex-1 overflow-y-auto">
          {isLoading ? (
            <div className="space-y-0.5">
              {Array.from({ length: 10 }).map((_, i) => (
                <SkeletonRow key={i} columns={3} />
              ))}
            </div>
          ) : drafts.length === 0 ? (
            <div className="p-8 text-center text-[#64748B] text-xs">No drafts found.</div>
          ) : drafts.map(draft => (
            <button key={draft.id} onClick={() => setSelectedDraft(draft)}
              className={cn(
                "w-full text-left p-4 border-b border-white/[0.04] hover:bg-white/[0.02] transition-all",
                selectedDraft?.id === draft.id && "bg-[#3B82F6]/5 border-l-2 border-l-[#3B82F6]"
              )}>
              <div className="flex items-start justify-between gap-2 mb-1.5">
                <p className="text-sm font-manrope font-medium text-[#E5ECF6] truncate">{draft.companyName}</p>
                <DraftStatusBadge status={draft.status} />
              </div>
              <p className="text-xs text-[#64748B] truncate mb-1">{draft.subject}</p>
              <p className="text-xs text-[#4B5563]">{timeAgo(draft.generatedAt)}</p>
            </button>
          ))}
        </div>
      </div>

      {/* Draft editor */}
      {selectedDraft && (
        <div className="flex-1 bg-[#0D1525] overflow-hidden flex flex-col">
          <DraftEditor 
            draft={selectedDraft} 
            onClose={() => setSelectedDraft(null)} 
            onUpdate={fetchDrafts} 
            onStatusChange={handleOptimisticStatus}
          />
        </div>
      )}

      {/* Batch Confirmations */}
      <ConfirmDialog
        isOpen={confirmBatchApprove}
        onClose={() => setConfirmBatchApprove(false)}
        onConfirm={executeBatchApprove}
        title="Batch Approve Drafts"
        description={`Are you sure you want to approve all pending drafts for "${activeCampaignName}"? This will mark them as ready for outreach.`}
        confirmText="Approve All"
      />

      <ConfirmDialog
        isOpen={confirmSendBatch}
        onClose={() => setConfirmSendBatch(false)}
        onConfirm={executeSendBatch}
        title="Send Outreach Batch"
        description={`You are about to send ${drafts.filter(d => d.status === 'approved').length} personalized messages for "${activeCampaignName}". This action cannot be undone.`}
        confirmText="Send Messages"
        variant="primary"
      />
    </div>
  );
}
