import type {
  Campaign,
  Lead,
  Agent,
  OutreachDraft,
  ActivityEvent,
  Report,
  AdminUser,
  AdminStats,
  Workspace,
} from "./types";

// ─── Workspace ─────────────────────────────────────────────────────────────
export const mockWorkspace: Workspace = {
  id: "ws_01",
  name: "Meridian Growth Co.",
  businessDescription: "B2B SaaS growth agency helping early-stage startups scale outbound acquisition.",
  businessType: "Agency",
  defaultOffer: "Done-for-you outbound lead generation and email automation",
  defaultRegion: "United States, Canada",
  outreachTone: "Professional, consultative, direct",
  plan: "Growth",
};

// ─── Campaigns ─────────────────────────────────────────────────────────────
export const mockCampaigns: Campaign[] = [
  {
    id: "camp_01",
    workspace_id: "ws_01",
    campaign_name: "SaaS Founders – Q4 Push",
    objective: "Book discovery calls with early-stage SaaS founders in North America",
    niche: "B2B SaaS",
    business_type: "Startup",
    target_region: "United States, Canada",
    ideal_lead_profile: "Founders of SaaS companies with 5–50 employees, Series A or bootstrapped, struggling with outbound",
    offer_context: "Done-for-you outbound systems",
    value_proposition: "We build and run your entire outbound engine in 30 days",
    outreach_tone: "Direct, strategic, founder-friendly",
    outreach_channel: "Cold Email",
    target_lead_count: 150,
    status: "running",
    current_stage: "outreach",
    leads_found: 127,
    qualified_leads: 84,
    drafts_created: 84,
    approvals_count: 61,
    created_at: "2024-11-02T09:00:00Z",
    updated_at: "2024-11-14T14:22:00Z",
  },
  {
    id: "camp_02",
    workspace_id: "ws_01",
    campaign_name: "E-commerce Ops Leaders",
    objective: "Identify and engage VP Operations at mid-market e-commerce brands",
    niche: "E-commerce",
    business_type: "Mid-market brand",
    target_region: "United Kingdom, Australia",
    ideal_lead_profile: "VPs or Directors of Operations at DTC brands doing $5M–$50M revenue",
    offer_context: "Operational efficiency consulting",
    value_proposition: "Cut fulfillment costs by 20% in 60 days or your money back",
    outreach_tone: "Data-driven, ROI-focused, executive-level",
    outreach_channel: "LinkedIn + Email",
    target_lead_count: 80,
    status: "needs_review",
    current_stage: "qualification",
    leads_found: 93,
    qualified_leads: 41,
    drafts_created: 0,
    approvals_count: 0,
    created_at: "2024-11-08T11:15:00Z",
    updated_at: "2024-11-13T16:40:00Z",
  },
  {
    id: "camp_03",
    workspace_id: "ws_01",
    campaign_name: "Legal Tech Decision-Makers",
    objective: "Generate warm pipeline for our LegalOps automation demo",
    niche: "Legal Technology",
    business_type: "Law Firm, Legal Department",
    target_region: "United States",
    ideal_lead_profile: "General Counsel or Legal Operations Manager at companies 200–2000 employees",
    offer_context: "LegalOps workflow automation",
    value_proposition: "Automate contract review in 72 hours",
    outreach_tone: "Professional, precise, compliance-aware",
    outreach_channel: "Cold Email",
    target_lead_count: 60,
    status: "completed",
    current_stage: "reporting",
    leads_found: 58,
    qualified_leads: 32,
    drafts_created: 32,
    approvals_count: 30,
    created_at: "2024-10-15T08:00:00Z",
    updated_at: "2024-11-01T10:00:00Z",
  },
  {
    id: "camp_04",
    workspace_id: "ws_01",
    campaign_name: "HR Leaders – Remote-First",
    objective: "Target CHROs and HR Directors at remote-first companies",
    niche: "Human Resources / People Ops",
    business_type: "Tech company (remote-first)",
    target_region: "United States, Europe",
    ideal_lead_profile: "CHROs or HR Directors at 100–500 person companies, remote-first culture",
    offer_context: "HR engagement and retention platform",
    value_proposition: "Reduce voluntary attrition by 35% in 90 days",
    outreach_tone: "Empathetic, people-first, research-backed",
    outreach_channel: "LinkedIn + Email",
    target_lead_count: 100,
    status: "draft",
    current_stage: "research",
    leads_found: 0,
    qualified_leads: 0,
    drafts_created: 0,
    approvals_count: 0,
    created_at: "2024-11-14T09:30:00Z",
    updated_at: "2024-11-14T09:30:00Z",
  },
  {
    id: "camp_05",
    workspace_id: "ws_01",
    campaign_name: "FinTech Risk Officers",
    objective: "Build pipeline for our compliance automation tool",
    niche: "Financial Technology",
    business_type: "FinTech, Bank, Credit Union",
    target_region: "United States",
    ideal_lead_profile: "Chief Risk Officers or Compliance Directors at FinTech companies 50–500 employees",
    offer_context: "AI-powered compliance monitoring",
    value_proposition: "Slash compliance review time by 60%",
    outreach_tone: "Formal, risk-aware, compliance-first",
    outreach_channel: "Cold Email",
    target_lead_count: 50,
    status: "failed",
    current_stage: "research",
    leads_found: 12,
    qualified_leads: 0,
    drafts_created: 0,
    approvals_count: 0,
    created_at: "2024-11-05T14:00:00Z",
    updated_at: "2024-11-06T09:20:00Z",
  },
];

// ─── Leads ─────────────────────────────────────────────────────────────────
export const mockLeads: Lead[] = [
  {
    id: "lead_01",
    companyName: "Stackify Inc.",
    website: "stackify.io",
    email: "alex@stackify.io",
    contactName: "Alex Turner",
    contactTitle: "Co-Founder & CEO",
    linkedIn: "linkedin.com/in/alexturner",
    score: 91,
    status: "qualified",
    qualificationReasoning: "Series A SaaS company struggling with outbound pipeline. CEO mentioned scaling challenges in podcast interview. Strong ICP fit. Budget signals positive.",
    tags: ["founder", "series-a", "saas", "outbound-pain"],
    campaignId: "camp_01",
    campaignName: "SaaS Founders – Q4 Push",
    draftStatus: "approved",
    region: "San Francisco, CA",
    niche: "B2B SaaS",
    summary: "Developer productivity SaaS. 28 employees. Bootstrapped Series A. Active on LinkedIn.",
    source: "Research Agent via LinkedIn + Crunchbase",
    createdAt: "2024-11-10T08:32:00Z",
  },
  {
    id: "lead_02",
    companyName: "Novara Labs",
    website: "novaralabs.com",
    email: "priya@novaralabs.com",
    contactName: "Priya Mehta",
    contactTitle: "Founder",
    linkedIn: "linkedin.com/in/priyamehta",
    score: 87,
    status: "qualified",
    qualificationReasoning: "Bootstrapped SaaS founder with clear outbound problem. Twitter activity shows active interest in growth strategies. Website shows weak conversion. Strong pain indicators.",
    tags: ["founder", "bootstrapped", "growth-focus"],
    campaignId: "camp_01",
    campaignName: "SaaS Founders – Q4 Push",
    draftStatus: "pending_review",
    region: "Austin, TX",
    niche: "B2B SaaS",
    summary: "HR automation SaaS. 14 employees. Bootstrapped. Revenue-generating.",
    source: "Research Agent via ProductHunt + LinkedIn",
    createdAt: "2024-11-10T09:14:00Z",
  },
  {
    id: "lead_03",
    companyName: "FlowBridge Co.",
    website: "flowbridge.co",
    email: "david.chen@flowbridge.co",
    contactName: "David Chen",
    contactTitle: "CEO",
    score: 78,
    status: "qualified",
    qualificationReasoning: "Early-stage SaaS, just raised seed round. CEO actively hiring sales team but no clear outbound motion. Timing is excellent for outbound systems pitch.",
    tags: ["founder", "seed-stage", "hiring"],
    campaignId: "camp_01",
    campaignName: "SaaS Founders – Q4 Push",
    draftStatus: "pending_review",
    region: "New York, NY",
    niche: "B2B SaaS",
    summary: "Workflow automation platform. 8 employees. Recently seed-funded ($2.1M).",
    source: "Research Agent via Crunchbase + AngelList",
    createdAt: "2024-11-11T10:45:00Z",
  },
  {
    id: "lead_04",
    companyName: "Velox Commerce",
    website: "veloxcommerce.com",
    email: "lisa.patel@veloxcommerce.com",
    contactName: "Lisa Patel",
    contactTitle: "VP Operations",
    score: 82,
    status: "qualified",
    qualificationReasoning: "DTC e-commerce brand with $12M revenue. VP Ops recently promoted, likely reviewing vendor relationships. Fulfillment pain signals from LinkedIn posts.",
    tags: ["dtc", "operations", "growth-stage"],
    campaignId: "camp_02",
    campaignName: "E-commerce Ops Leaders",
    draftStatus: "pending_review",
    region: "London, UK",
    niche: "E-commerce",
    summary: "DTC fashion and accessories. ~150 employees. $12M revenue. UK-based.",
    source: "Research Agent via LinkedIn Sales Navigator",
    createdAt: "2024-11-12T11:20:00Z",
  },
  {
    id: "lead_05",
    companyName: "Matterhorn Digital",
    website: "matterhorndigital.com",
    email: "james@matterhorndigital.com",
    contactName: "James Whitmore",
    contactTitle: "Director of Operations",
    score: 65,
    status: "new",
    qualificationReasoning: "E-commerce brand in review. Revenue unconfirmed. Director title confirmed. Need additional data points before qualifying.",
    tags: ["ecommerce", "operations", "pending_review"],
    campaignId: "camp_02",
    campaignName: "E-commerce Ops Leaders",
    draftStatus: "pending_review",
    region: "Sydney, Australia",
    niche: "E-commerce",
    summary: "Consumer electronics e-commerce. Estimated 80 employees.",
    source: "Research Agent via LinkedIn",
    createdAt: "2024-11-12T14:33:00Z",
  },
  {
    id: "lead_06",
    companyName: "Carthage Legal Group",
    website: "carthagelegal.com",
    email: "rachel.kim@carthagelegal.com",
    contactName: "Rachel Kim",
    contactTitle: "General Counsel",
    score: 88,
    status: "qualified",
    qualificationReasoning: "Large law firm with significant manual contract review workload. GC has spoken publicly about workflow inefficiency. Strong ICP, budget likely available.",
    tags: ["legal", "enterprise", "gc"],
    campaignId: "camp_03",
    campaignName: "Legal Tech Decision-Makers",
    draftStatus: "approved",
    region: "Chicago, IL",
    niche: "Legal Technology",
    summary: "Full-service law firm. 400+ attorneys. Heavy contract volume.",
    source: "Research Agent via LinkedIn + Bar Association Directory",
    createdAt: "2024-10-20T08:00:00Z",
  },
];

// ─── Agents ────────────────────────────────────────────────────────────────
export const mockAgents: Agent[] = [
  {
    id: "agent_research",
    type: "research",
    name: "Research Agent",
    role: "Discovers and profiles qualified leads from web sources, LinkedIn, directories, and databases.",
    status: "idle",
    tasksCompleted: 347,
    lastActive: "2024-11-14T14:22:00Z",
    metrics: [
      { label: "Leads Sourced", value: 347 },
      { label: "Sources Indexed", value: 12 },
      { label: "Avg. Time / Lead", value: "2.3 min" },
    ],
  },
  {
    id: "agent_qualification",
    type: "qualification",
    name: "Qualification Agent",
    role: "Scores and qualifies leads using ICP rules, signals, and reasoning. Produces qualification reports per lead.",
    status: "running",
    tasksCompleted: 218,
    lastActive: "2024-11-14T14:55:00Z",
    currentTask: "Scoring 23 leads from E-commerce Ops campaign",
    metrics: [
      { label: "Leads Scored", value: 218 },
      { label: "Avg. Score", value: 79 },
      { label: "Qualification Rate", value: "64%" },
    ],
  },
  {
    id: "agent_outreach",
    type: "outreach",
    name: "Outreach Agent",
    role: "Generates personalized outreach drafts per lead using ICP context, lead summary, and campaign tone.",
    status: "running",
    tasksCompleted: 156,
    lastActive: "2024-11-14T15:01:00Z",
    currentTask: "Generating drafts for SaaS Founders campaign batch 3",
    metrics: [
      { label: "Drafts Created", value: 156 },
      { label: "Approval Rate", value: "73%" },
      { label: "Avg. Personalization", value: "High" },
    ],
  },
  {
    id: "agent_reporting",
    type: "reporting",
    name: "Reporting Agent",
    role: "Generates structured campaign reports with metrics, bottlenecks, and recommendations after completion.",
    status: "idle",
    tasksCompleted: 8,
    lastActive: "2024-11-01T10:00:00Z",
    metrics: [
      { label: "Reports Generated", value: 8 },
      { label: "Campaigns Covered", value: 3 },
      { label: "Avg. Report Time", value: "4.2 min" },
    ],
  },
  {
    id: "agent_manager",
    type: "manager",
    name: "Manager Agent",
    role: "Orchestrates the Agent-Net workflow. Routes tasks, resolves blockers, and coordinates between agents.",
    status: "running",
    tasksCompleted: 1042,
    lastActive: "2024-11-14T15:02:00Z",
    currentTask: "Coordinating outreach batch for camp_01",
    metrics: [
      { label: "Tasks Routed", value: 1042 },
      { label: "Blocker Resolutions", value: 34 },
      { label: "Active Pipelines", value: 2 },
    ],
  },
];

// ─── Activity Feed ──────────────────────────────────────────────────────────
export const mockActivity: ActivityEvent[] = [
  {
    id: "act_01",
    agentType: "outreach",
    agentName: "Outreach Agent",
    event: "Drafts batch complete",
    detail: "Generated 23 personalized outreach drafts for SaaS Founders Q4 campaign.",
    timestamp: "2024-11-14T15:01:00Z",
    campaignId: "camp_01",
    campaignName: "SaaS Founders – Q4 Push",
    type: "success",
  },
  {
    id: "act_02",
    agentType: "qualification",
    agentName: "Qualification Agent",
    event: "Qualification review needed",
    detail: "41 leads scored for E-commerce Ops campaign. 12 leads flagged for manual review — ambiguous ICP signals.",
    timestamp: "2024-11-14T14:40:00Z",
    campaignId: "camp_02",
    campaignName: "E-commerce Ops Leaders",
    type: "warning",
  },
  {
    id: "act_03",
    agentType: "manager",
    agentName: "Manager Agent",
    event: "Workflow stage advanced",
    detail: "SaaS Founders campaign moved from Qualification to Outreach stage.",
    timestamp: "2024-11-14T14:22:00Z",
    campaignId: "camp_01",
    campaignName: "SaaS Founders – Q4 Push",
    type: "info",
  },
  {
    id: "act_04",
    agentType: "research",
    agentName: "Research Agent",
    event: "Research complete",
    detail: "Found 93 leads for E-commerce Ops campaign. 5 sources indexed: LinkedIn, Apollo, Hunter.io, Crunchbase, Company websites.",
    timestamp: "2024-11-13T16:40:00Z",
    campaignId: "camp_02",
    campaignName: "E-commerce Ops Leaders",
    type: "success",
  },
  {
    id: "act_05",
    agentType: "research",
    agentName: "Research Agent",
    event: "Agent failed",
    detail: "FinTech Risk Officers campaign research failed. API rate limit exceeded on LinkedIn source. Retry required.",
    timestamp: "2024-11-06T09:20:00Z",
    campaignId: "camp_05",
    campaignName: "FinTech Risk Officers",
    type: "error",
  },
  {
    id: "act_06",
    agentType: "reporting",
    agentName: "Reporting Agent",
    event: "Report generated",
    detail: "Campaign report for Legal Tech Decision-Makers is ready. 32 qualified leads, 30 approved drafts, 94% draft approval rate.",
    timestamp: "2024-11-01T10:00:00Z",
    campaignId: "camp_03",
    campaignName: "Legal Tech Decision-Makers",
    type: "success",
  },
];

// ─── Outreach Drafts ────────────────────────────────────────────────────────
export const mockDrafts: OutreachDraft[] = [
  {
    id: "draft_01",
    leadId: "lead_01",
    leadName: "Alex Turner",
    companyName: "Stackify Inc.",
    campaignId: "camp_01",
    campaignName: "SaaS Founders – Q4 Push",
    subject: "Outbound system for Stackify – 30-day build",
    openingLine: "Saw your ProductHunt launch last month — congrats on the traction.",
    body: "Building a repeatable outbound engine is one of the hardest early problems for SaaS founders, especially when you're still product-focused.\n\nWe build and run the entire outbound system for founders — lead sourcing, qualification, personalized sequencing, and inbox management — in 30 days.\n\nNo hiring. No tooling headaches. Just a working pipeline.\n\nWe did this for three Series A SaaS companies in Q3 and generated 40+ qualified discovery calls for each in the first 60 days.",
    cta: "Worth a 20-min call to see if it fits where Stackify is right now?",
    followUp: "Just following up on this — still relevant if you're thinking about outbound heading into Q4.",
    tone: "Direct, founder-friendly",
    status: "approved",
    generatedAt: "2024-11-12T10:00:00Z",
    generatedBy: "Outreach Agent",
  },
  {
    id: "draft_02",
    leadId: "lead_02",
    leadName: "Priya Mehta",
    companyName: "Novara Labs",
    campaignId: "camp_01",
    campaignName: "SaaS Founders – Q4 Push",
    subject: "Outbound pipeline for Novara Labs",
    openingLine: "Noticed you've been building in the HR automation space — great timing given where the market is heading.",
    body: "Getting your first outbound motion right is a leverage point most founders undervalue until they're trying to fix it later.\n\nWe help bootstrapped SaaS founders stand up a full outbound system — lead research, qualification, personalized email sequences — in 30 days without adding headcount.\n\nThe founders we work with typically see their first qualified conversations within 3 weeks of launch.",
    cta: "Happy to share exactly what this looked like for a similar HR SaaS founder if you're open to a quick call.",
    tone: "Strategic, founder-peer",
    status: "pending_review",
    generatedAt: "2024-11-13T09:00:00Z",
    generatedBy: "Outreach Agent",
  },
  {
    id: "draft_03",
    leadId: "lead_03",
    leadName: "David Chen",
    companyName: "FlowBridge Co.",
    campaignId: "camp_01",
    campaignName: "SaaS Founders – Q4 Push",
    subject: "FlowBridge outbound — scaling after seed",
    openingLine: "Congrats on the seed round — that stage is where outbound becomes the highest-leverage growth move.",
    body: "Post-seed, the pressure to show pipeline velocity is real. Most founders start hiring BDRs, but that's a 6-month ramp before you see results.\n\nWe build the outbound system instead — sourcing, scoring, and personalizing at scale — so you get pipeline activity in the first 30 days.\n\nWe recently worked with two workflow automation founders post-seed and generated 28 and 34 discovery calls respectively within 45 days.",
    cta: "Let me know if it's worth exploring for FlowBridge — happy to do a quick 15-min fit check.",
    tone: "Direct, strategic",
    status: "pending_review",
    generatedAt: "2024-11-13T09:45:00Z",
    generatedBy: "Outreach Agent",
  },
];

// ─── Reports ────────────────────────────────────────────────────────────────
export const mockReports: Report[] = [
  {
    id: "report_01",
    campaignId: "camp_03",
    campaignName: "Legal Tech Decision-Makers",
    generatedAt: "2024-11-01T10:00:00Z",
    leadsFound: 58,
    qualifiedLeads: 32,
    qualificationRate: 55.2,
    draftsGenerated: 32,
    pendingApprovals: 2,
    workflowTime: "17 days",
    bottlenecks: [
      "Qualification stage took 4 days longer than average due to complex ICP signals in legal sector",
      "2 outreach drafts pending final approval"
    ],
    recommendations: [
      "Expand target to include In-House Legal Ops Managers at tech companies for higher volume",
      "Adjust qualification scoring to weight LinkedIn activity higher for legal professionals",
      "Consider a multi-touch sequence (email + LinkedIn) for this niche"
    ],
    summary: "Strong campaign performance with a 55% qualification rate. Draft approval rate of 94% indicates excellent outreach quality. Legal sector requires longer qualification cycles but yields high-intent leads.",
  },
  {
    id: "report_02",
    campaignId: "camp_01",
    campaignName: "SaaS Founders – Q4 Push",
    generatedAt: "2024-11-14T12:00:00Z",
    leadsFound: 127,
    qualifiedLeads: 84,
    qualificationRate: 66.1,
    draftsGenerated: 84,
    pendingApprovals: 23,
    workflowTime: "In Progress",
    bottlenecks: [
      "Outreach approval queue has 23 pending items — bottleneck at review stage",
    ],
    recommendations: [
      "Clear the outreach review queue — 23 high-intent leads waiting for approved outreach",
      "Consider auto-approve threshold for leads scored 85+ to reduce bottleneck",
    ],
    summary: "Campaign running well. Research and qualification complete with 66% qualification rate. Currently at outreach stage — 23 drafts awaiting user approval before sending.",
  },
];

// ─── Admin Data ─────────────────────────────────────────────────────────────
export const mockAdminStats: AdminStats = {
  totalUsers: 284,
  totalWorkspaces: 91,
  totalCampaigns: 433,
  activeRuns: 17,
  failedRuns: 8,
  totalDrafts: 12847,
};

export const mockAdminUsers: AdminUser[] = [
  { id: "u_01", name: "Jordan Pierce", email: "jordan@meridian.co", workspace: "Meridian Growth Co.", plan: "Growth", status: "active", joinedAt: "2024-09-10", campaignCount: 5 },
  { id: "u_02", name: "Samira Okafor", email: "samira@apex.io", workspace: "Apex Ventures", plan: "Starter", status: "active", joinedAt: "2024-10-02", campaignCount: 2 },
  { id: "u_03", name: "Chris Nakamura", email: "chris@launchfast.com", workspace: "LaunchFast Agency", plan: "Growth", status: "active", joinedAt: "2024-10-15", campaignCount: 7 },
  { id: "u_04", name: "Elena Vasquez", email: "elena@vantage.ai", workspace: "Vantage AI", plan: "Enterprise", status: "active", joinedAt: "2024-08-28", campaignCount: 14 },
  { id: "u_05", name: "Marcus Reid", email: "marcus@bluerock.io", workspace: "Bluerock Solutions", plan: "Starter", status: "inactive", joinedAt: "2024-11-01", campaignCount: 1 },
];
